### ISSUE TITLE
[Feature request] Panel indicator

### ISSUE THREAD

**Issue by ViBE-HU** [gpawru/touchpad#2]
First of all: finally a working extension!

Also it would be nice if you can add an indicator icon which could show the actual status of the touchpad.

**Comment by gpawru** [comment]
Thank you, I’m very glad my extension has been useful! Regarding the indicator – in GNOME, I found built-in icons for the touchpad, disabled touchpad, and mouse. I’m currently using those in the popup. There’s no specific icon for the case when the touchpad doesn’t work while the mouse is connected. I could draw the icons myself – I’ve spent part of my life in design (UI/UX in particular). However, it’s important to consider the various GNOME themes, and as a result, it will take me some time to work through this. I also think I’ll need to add a configuration option to the extension for enabling/disabling the indicators.

P.S. This is a micro side project I originally created for my own convenience, and only later thought, why not share it? Most of my time is dedicated to my main project. Also, by nature, I don’t release anything without thoroughly studying the details. So, I apologize in advance if I don’t respond quickly, but I’ve added this to my to-do list and will include the indicators in the next update.

**Comment by ViBE-HU** [comment]
I absolutely understand. These are just my suggestions. Since I have no space and ideal environment to use desktop machines I have to use laptops. And basically all old extensions are dead. So I am pretty happy with this one and thought you might add some basic features for better integrity. Of course the indicator should be optional as usual. Thanks for your reply.

**Comment by gpawru** [comment]
"It would be really great if you could keep helping me with writing extensions and contributing to the community. But today, my task is to have a few drinks and reflect on missed opportunities — I just turned 40 today, damn it!

**Comment by ViBE-HU** [comment]
Nice. Hope you had enough amount of drinks and survived this major milestone :D

**Comment by gpawru** [comment]
@ViBE-HU updated, pending review on extensions.gnome.org. Indicator can now be toggled on/off in the extension settings.
